apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: myapp-k8s
    spec:
      containers:
        - name: myapp-k8s
          image: shridhar143/myapp:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4499 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: myapp-k8ssvc
spec:
  selector:
    app: myapp-k8s
  ports:
    - protocol: "TCP"
      port: 4499 # The port that the service is running on in the cluster
      targetPort: 4499 # The port exposed by the service
  type: NodePort # type of the service.
